//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_vyb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class given_vaccine
    {
        public string given_id { get; set; }
        public string username { get; set; }
        public string vac_id { get; set; }
        public System.DateTime given_date { get; set; }
    
        public virtual vaccine vaccine { get; set; }
        public virtual user user { get; set; }
    }
}
