//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_vyb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaccine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vaccine()
        {
            this.given_vaccine = new HashSet<given_vaccine>();
        }
    
        public string vac_id { get; set; }
        public string vac_name { get; set; }
        public int due_months { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<given_vaccine> given_vaccine { get; set; }
    }
}
